name = "devnet-sgforms-worker"
type = "webpack"

account_id = "149f3f176965c9f84fb12b9a9d5db590"
workers_dev = true
route = ""
zone_id = ""

# [secrets]
# FORM_KEY
# FORM_ID
# POST_URL
# TEST_FORM_KEY